### ISSUE TITLE
link css stylesheet

### ISSUE THREAD

**Issue by mikebutts** [LyellScott/prj-rev-bwfs-dasmoto#5]
https://github.com/LyellScott/prj-rev-bwfs-dasmoto/blob/b763f7e9f4febbd75845c7c48cbe79f07f4635b5/DasmotosArtsCrafts/index.html#L6

Be careful when you using caps in your paths, if you mismatch them it will not work, to stay safe I use all lowercase.

**Comment by LyellScott** [comment]
OK thanks
